### ISSUE TITLE
User can view the letters to type.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/typing-test#1]
# Motivation

We want to be able to see what needs to be typed.

# Task Implementation

- [x] make the files necessary
- [x] link files as necessary
- [x] create HTML
- [x] write the text
