### ISSUE TITLE
User can click or hover on a state and get feedback from it. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/typing-test#11]
# Motivation
Now that we have a map that we can see, we want to be able to start interactive with this. We want to be able to able to adjust the map to our liking. 

# Task Implementation 
- [ ] Grab event listeners from the map
- [ ] Implement classes in order to get the states information. 
- [ ] Implement a function to tell us that we clicked on a state.
