### ISSUE TITLE
User can type a letter and get feedback

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/typing-test#3]
# Motivation

Now that we can see what letter we're on we want to see some action

# Task Implementation
- [x] be able to position the current key correctly. 
- [x] be able to press a key and get a response. 
- [x] be able to indicate that the key was the right one
- [x] be able to change the text when the right key is pressed
- [x] be able to type the whole phrase
