### ISSUE TITLE
User can complete a test and view a score.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/typing-test#4]
# Motivation 
Now that all the previous steps are completed we want to be able to complete this exercise by tying it all up.

# Task Implementation
- [x] Display the number of keys typed overall. 
- [x] Display the number of keys pressed correctly. 
- [x] be able to update the number of keys pressed with each keystroke on the page.
- [x] be able to indicate that the user has completed the task. 
- [x] be able to calculate an accuracy score correctly, calculated as (number of keys pressed correctly)  / (number of keys pressed overall)
