### ISSUE TITLE
User can see a visually appealing game

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/typing-test#9]
# Motiviation 
Now that we have basic functionality of the game itself, we want to have the game be visually appealing to the user who plays it. We will be increasing its responsiveness and adding some more layout.

# Task Implementation
- [x] Change the colors of the background of the page
- [x] Use different fonts for each element
- [x] Space out elements correctly to remove the whitespacing. 
- [x] Be able to view instructions for the test. 
- [x] Be able to indicate that we're currently on a spacebar character
